# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI


name: Docker Builder
on:
  push:
    branches:
      - main
      - test
  release:
    types: [published]

jobs:
  docker:
    if: ${{ vars.SKIP_DOCKER_JOB != 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          # --> telegraf
          - TAGNAME: ""
            REPOSITORY: telegraf
            EXTRA_CMAKE_ARGS: ""
            MARCH: ""
            PLATFORM: amd64
            UHD_VERSION: ""
            DPDK_VERSION: ""
            DOCKERFILE: ./docker/telegraf/Dockerfile
            CONTEXT: ./docker/telegraf
            ATTESTATION_FILE: ""
          # --> grafana
          - TAGNAME: ""
            REPOSITORY: grafana
            EXTRA_CMAKE_ARGS: ""
            MARCH: ""
            PLATFORM: amd64
            UHD_VERSION: ""
            DPDK_VERSION: ""
            DOCKERFILE: ./docker/grafana/Dockerfile
            CONTEXT: ./docker/grafana
            ATTESTATION_FILE: ""
          # --> gnb
          # AMD AVX2
          - TAGNAME: release_avx2
            REPOSITORY: ocudu
            MARCH: x86-64-v3
            PLATFORM: amd64
            UHD_VERSION: "4.7.0.0"
            DPDK_VERSION: "24.11.2"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
            ATTESTATION_FILE: /usr/local/share/ocudu.spdx
          - TAGNAME: release_with_debug_avx2
            REPOSITORY: ocudu
            EXTRA_CMAKE_ARGS: -DFORCE_DEBUG_INFO=On
            MARCH: x86-64-v3
            PLATFORM: amd64
            UHD_VERSION: "4.7.0.0"
            DPDK_VERSION: "24.11.2"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
            ATTESTATION_FILE: /usr/local/share/ocudu.spdx
          # AMD AVX512
          - TAGNAME: release_avx512
            REPOSITORY: ocudu
            MARCH: x86-64-v4
            PLATFORM: amd64
            UHD_VERSION: "4.7.0.0"
            DPDK_VERSION: "24.11.2"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
            ATTESTATION_FILE: /usr/local/share/ocudu.spdx
          - TAGNAME: release_with_debug_avx512
            REPOSITORY: ocudu
            EXTRA_CMAKE_ARGS: -DFORCE_DEBUG_INFO=On
            MARCH: x86-64-v4
            PLATFORM: amd64
            UHD_VERSION: "4.7.0.0"
            DPDK_VERSION: "24.11.2"
            DOCKERFILE: ./docker/Dockerfile
            CONTEXT: ./
            ATTESTATION_FILE: /usr/local/share/ocudu.spdx
    env:
      PREFIX: ghcr.io/netsys-edinburgh/${{ matrix.REPOSITORY }}:${{ matrix.TAGNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine tags based on branch
        id: tags
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          DATE_TAG="${GITHUB_SHA:0:10}__$(date +'%Y-%m-%d')"
          RELEASE_NAME_INIT="${{ github.event.release.name }}"
          RELEASE_NAME="${RELEASE_NAME_INIT##* }"

          if [ -n "$RELEASE_NAME" ]; then
            tags="${{ env.PREFIX }}-${DATE_TAG},${{ env.PREFIX }}-${RELEASE_NAME}"
          else
            if [ "$BRANCH_NAME" == "main" ]; then
              tags="${{ env.PREFIX }}-${DATE_TAG},${{ env.PREFIX }}-latest"
            elif [ "$BRANCH_NAME" == "test" ]; then
              tags="${{ env.PREFIX }}-${DATE_TAG},${{ env.PREFIX }}-next"
            fi
          fi
          tags="${tags//:-/:}"
          echo "tags=$tags"
          echo "tags=$tags" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          file: ${{ matrix.DOCKERFILE }}
          platforms: ${{ matrix.PLATFORM }}
          context: ${{ matrix.CONTEXT }}
          build-args: |
            UHD_VERSION=${{ matrix.UHD_VERSION }}
            DPDK_VERSION=${{ matrix.DPDK_VERSION }}
            MARCH=${{ matrix.MARCH }}
            ENABLE_UHD=Off
